SELECT *
FROM STUDENTS
WHERE YEAR_ADMITTED>'2015-01-01' AND CGPA>3.1;
SELECT *
FROM STUDENTS
WHERE YEAR(YEAR_ADMITTED)<2015 AND CGPA>3.1;
SELECT *
FROM STUDENTS
WHERE YEAR(YEAR_ADMITTED)<2015 AND CGPA>3.1;
SELECT *
FROM STUDENTS
WHERE AGE>26 AND CGPA>3.1;
SELECT *
FROM STUDENTS
WHERE STUDENT_NAME LIKE '_M%'
OR CGPA >'3.1';
SELECT *
FROM STUDENTS
WHERE AGE>20
OR CGPA >3.1
OR YEAR (YEAR_ADMITTED)>2017;
SELECT *
FROM STUDENTS
WHERE NOT CGPA>=3.8;
SELECT *
FROM STUDENTS
WHERE NOT CGPA>=3.8 AND NOT AGE>=25;
SELECT *
FROM STUDENTS
WHERE AGE=23 OR AGE=24 OR AGE=27;
- - WITH THE IN KEYWORD, INSTEAD OF USING ALL THOSE ORs, WE CAN SIMPLIFY OUR QUERY WTITH THE IN KEYWORD.
SO WE USE THE IN KEYWORD AS A SHORTHAND FOR MULTIPLE ORs
SELECT *
FROM STUDENTS
WHERE AGE IN (23,24,27);
SELECT *
FROM STUDENTS
WHERE AGE NOT IN(18);
SELECT *
FROM STUDENTS
WHERE YEAR(YEAR_ADMITTED) NOT IN (2015, 2020);
SELECT *
FROM STUDENTS
WHERE STUDENT_NAME LIKE '__d';
SELECT *
FROM STUDENTS
WHERE AGE BETWEEN 23 AND 27;
SELECT *
FROM STUDENTS
WHERE YEAR(YEAR_ADMITTED) BETWEEN '2015' AND '2017';
SELECT *
FROM STUDENTS
WHERE YEAR(YEAR_ADMITTED) BETWEEN '2015-01-01' AND '2017-01-01';
SELECT *
FROM STUDENTS
WHERE AGE NOT BETWEEN '24' AND '27';
SELECT *
FROM STUDENTS
WHERE YEAR(YEAR_ADMITTED) NOT BETWEEN '2015' AND '2017';
SELECT *
FROM STUDENTS
WHERE YEAR(YEAR_ADMITTED) BETWEEN '2015' AND '2017'
AND AGE IN(23,35);
SELECT *
FROM STUDENTS
WHERE YEAR(YEAR_ADMITTED) BETWEEN '2015' AND '2017'
AND AGE NOT IN(23,35);
SELECT *
FROM STUDENTS
WHERE AGE IS NULL;
SELECT *
FROM STUDENTS
WHERE AGE IS NOT NULL;
SELECT *
FROM STUDENTS
WHERE STUDENT_NAME IS NOT NULL;
SELECT *
CASE
	WHEN CONDITION1 THEN RESULT 1
    WHEN CONDITION2 THEN RESULT2
    WHEN CONDITION3 THEN RESULT3
    ELSE RESULT
END
FROM TABLE_NAME;

SELECT *,
CASE
	WHEN(AGE>=26) THEN 'Upper Age Class'
    WHEN(AGE BETWEEN 23 AND 25) THEN 'Middle Age Class'
    ELSE 'Lower Age Class'
END AS 'Age Label'
FROM STUDENTS;
Select*,
Case CGPA
	WHEN 5.00 THEN 'Best Student'
ELSE 'nomal'
END AS 'AWARDEES'
FROM Students;
SELECT*,
CASE
	WHEN (CGPA BETWEEN 4.50 AND 5.00) THEN 'FIRST CLASS'
    WHEN (CGPA BETWEEN 3.50 AND 4.49) THEN 'SECOND CLASS UPPER'
    WHEN (CGPA BETWEEN 2.40 AND 3.49) THEN 'SECOND CLASS LOWER'
    WHEN (CGPA BETWEEN 1.50 AND 2.39) THEN 'THIRD CLASS'
    WHEN (CGPA BETWEEN 1.00 AND 1.49) THEN 'PASS'
    ELSE'PROBATION'
END AS 'AWARDEES'
FROM Students;